### ISSUE TITLE
Error on successful D-Bus call

### ISSUE THREAD

**Issue by zeenix** [antoyo/dbus-macros-rs#7]
I have the following code (it assume the PR i submitted earlier):

```
use dbus;
use dbus_macros;

dbus_interface!("org.freedesktop.Avahi.Server", interface Server {
    fn EntryGroupNew() -> String;
});

pub fn publish() -> Result<(),dbus::Error> {
    let server = Server::new("org.freedesktop.Avahi", Some("/"), dbus::BusType::System);

    // FIXME: Make this async when it's possible
    let group_path = server.EntryGroupNew()?;
    println!("group: {}", group_path);

    Ok(())
}
```

But I get an error on runtime:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   1:     0x56297977b49a - std::sys::imp::backtrace::tracing::imp::write::hd9cb4c1797101742
   2:     0x56297977d802 - std::panicking::default_hook::{{closure}}::h154dea97b11a961f
   3:     0x56297977d3d7 - std::panicking::default_hook::h7b2373844128ce08
   4:     0x56297977dbf1 - std::panicking::rust_panic_with_hook::h8d52d23c1df454da
   5:     0x56297977da34 - std::panicking::begin_panic::h031e0a076e248818
   6:     0x56297977d9a9 - std::panicking::begin_panic_fmt::hcd972326ec953c01
   7:     0x56297977d937 - rust_begin_unwind
   8:     0x562979787cbd - core::panicking::panic_fmt::h519452995771b90d
   9:     0x562979787bf4 - core::panicking::panic::h22b1ce4468ab1d51
  10:     0x56297974bdb9 - <core::option::Option<T>>::unwrap::haf3c34ffc6e2f4b0
                        at /builddir/build/BUILD/rustc-1.15.1-src/src/libcore/macros.rs:21
  11:     0x5629797595de - gps_share::avahi::Server::EntryGroupNew::h9d39588b9afb2632
                        at /home/zeenix/checkout/gnome/gps-share/src/avahi.rs:27
  12:     0x562979758713 - gps_share::avahi::publish::heb15ba5d63934b45
                        at /home/zeenix/checkout/gnome/gps-share/src/avahi.rs:48
  13:     0x562979757efb - gps_share::server::Server::run::he7c19064abce934d
                        at /home/zeenix/checkout/gnome/gps-share/src/server.rs:46
  14:     0x562979758e57 - gps_share::main::h38c6f0d6672ea359
                        at /home/zeenix/checkout/gnome/gps-share/src/main.rs:52
  15:     0x5629797860ea - __rust_maybe_catch_panic
  16:     0x56297977e1d1 - std::rt::lang_start::h654cbbacaf320c39
  17:     0x562979759802 - main
  18:     0x7fc5957a9400 - __libc_start_main
  19:     0x56297974aef9 - _start
  20:                0x0 - <unknown>

```
I checked on `busctl monitor` and saw the method successfully returning a string, as expected. So it's something with the macro.

**Comment by zeenix** [comment]
Turns out the dbus crate has special type for object path and we were asking for string. Combined with latest dbus and update the sample code to use ObjectPath type, this issue is no longer reproducible.
